### ISSUE TITLE
ArConnect not fully connecting with arns.app

### ISSUE THREAD

**Issue by tapirtoken** [th8ta/ArConnect#362] opened 2024-06-04 04:02 UTC
Not sure how much of the problem is due to ArConnect vs. ArNS so here's the issue:

https://github.com/ar-io/arns-service/issues/118

**Comment by t8** [comment] 2024-06-20 03:22
Hey @tapirtoken, did some reading on the issue you linked above. Few notes in response:

- It looks like there are two separate issues: arns.app loading data properly and ArConnect loading data properly. The good news is that arns.app isn't pulling token data from ArConnect, so these two issues are unrelated. Will default to the ario team for anything arns.app related. On the ArConnect side, there have recently been some restrictions and rate limits placed around Warp infrastructure, which I'm guessing is to save on costs as they help their users migrate to AO. In the meantime this could very well mean balances won't load in ArConnect. One other possibility is that your requests to Warp are being blocked. Unsure if you're on a VPN or a blacklisted IP, but we're unable to reproduce what you're seeing with tIO in ArConnect ourselves.
- In either case, both ario and Warp are in the process of moving over to support AO. Eventually we plan to deprecate Warp token support inside of ArConnect and neither of these problems will be relevant since all will be on AO and in working order.

Appreciate the report and happy to answer any questions you have! Will close this issue for now.

**Closed as not planned by t8** 2024-06-20 03:22 UTC
